
apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
data:
    nginx.conf: |
		server {
            listen       80;
            server_name  127.0.0.1;
            access_log  /usr/locall/nginx/logs/access.log;
            error_log  /var/log/nginx/error.log main;

		location / {
            root   /k8s/data/php;
            index  index.html index.htm index.php;
            }

		location ~ \.php$ {
            root   /k8s/data/php;
            fastcgi_pass   php-service:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
            }
		}
